channels:
- conda-forge
dependencies:
- python=3.8.19
- pip<=23.3.1
- pip:
  - mlflow==2.12.2
  - cloudpickle==3.0.0
  - importlib-metadata==7.0.1
  - numpy==1.24.3
  - packaging==23.2
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.10.1
name: mlflow-env
